# Generated by Django 4.0.6 on 2022-07-18 08:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cafeteria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NAME', models.CharField(max_length=15)),
            ],
            options={
                'db_table': 'CAFETERIA_TB',
            },
        ),
        migrations.CreateModel(
            name='Corner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NAME', models.CharField(max_length=10)),
                ('CAFETERIA', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='CORNER_FK', to='api.cafeteria')),
            ],
            options={
                'db_table': 'CORNER_TB',
            },
        ),
        migrations.CreateModel(
            name='Division',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NAME', models.CharField(max_length=15)),
            ],
            options={
                'db_table': 'DIVISION_TB',
            },
        ),
        migrations.CreateModel(
            name='Slot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SLOT', models.CharField(max_length=5)),
                ('START', models.TimeField()),
                ('END', models.TimeField()),
                ('CAFETERIA', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='SLOT_FK', to='api.cafeteria')),
            ],
            options={
                'db_table': 'SLOT_TB',
            },
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MENU', models.CharField(max_length=100)),
                ('DATE', models.DateField()),
                ('CORNER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='MENU_CORNER_FK', to='api.corner')),
                ('SLOT', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='MENU_SLOT_FK', to='api.slot')),
            ],
            options={
                'db_table': 'MENU_TB',
            },
        ),
        migrations.AddField(
            model_name='cafeteria',
            name='DIVISION',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='DIVISION_FK', to='api.division'),
        ),
    ]
